<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Gordon Wright &amp; Professor Danielle Navarro">

<title>PS51020A – Data Visualisation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PS51020A</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">General Info</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-instructors" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Instructors</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-instructors">    
        <li>
    <a class="dropdown-item" href="https://www.littlemonkeylab.com/">
 <span class="dropdown-text">Gordon Wright</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Data Visualisation</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Quarto Example</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Index</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Course Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../materials/home_week02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2 Content</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../materials/scalequestions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scale Questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../materials/choicequestions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choice Questions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../materials/freetextquestions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Free Text</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#graphics" id="toc-graphics" class="nav-link active" data-scroll-target="#graphics">Drawing graphs</a>
  <ul class="collapse">
  <li><a href="#introplotting" id="toc-introplotting" class="nav-link" data-scroll-target="#introplotting">An introduction to plotting</a>
  <ul class="collapse">
  <li><a href="#a-tedious-digression" id="toc-a-tedious-digression" class="nav-link" data-scroll-target="#a-tedious-digression">A tedious digression</a></li>
  <li><a href="#figtitles" id="toc-figtitles" class="nav-link" data-scroll-target="#figtitles">Customising the title and the axis labels</a></li>
  <li><a href="#changing-the-plot-type" id="toc-changing-the-plot-type" class="nav-link" data-scroll-target="#changing-the-plot-type">Changing the plot type</a></li>
  <li><a href="#changing-other-features-of-the-plot" id="toc-changing-other-features-of-the-plot" class="nav-link" data-scroll-target="#changing-other-features-of-the-plot">Changing other features of the plot</a></li>
  <li><a href="#changing-the-appearance-of-the-axes" id="toc-changing-the-appearance-of-the-axes" class="nav-link" data-scroll-target="#changing-the-appearance-of-the-axes">Changing the appearance of the axes</a></li>
  <li><a href="#dont-panic" id="toc-dont-panic" class="nav-link" data-scroll-target="#dont-panic">Don’t panic</a></li>
  </ul></li>
  <li><a href="#hist" id="toc-hist" class="nav-link" data-scroll-target="#hist">Histograms</a>
  <ul class="collapse">
  <li><a href="#visual-style-of-your-histogram" id="toc-visual-style-of-your-histogram" class="nav-link" data-scroll-target="#visual-style-of-your-histogram">Visual style of your histogram</a></li>
  </ul></li>
  <li><a href="#stem" id="toc-stem" class="nav-link" data-scroll-target="#stem">Stem and leaf plots</a></li>
  <li><a href="#boxplots" id="toc-boxplots" class="nav-link" data-scroll-target="#boxplots">Boxplots</a>
  <ul class="collapse">
  <li><a href="#visual-style-of-your-boxplot" id="toc-visual-style-of-your-boxplot" class="nav-link" data-scroll-target="#visual-style-of-your-boxplot">Visual style of your boxplot</a></li>
  <li><a href="#boxplotoutliers" id="toc-boxplotoutliers" class="nav-link" data-scroll-target="#boxplotoutliers">Using box plots to detect outliers</a></li>
  <li><a href="#multipleboxplots" id="toc-multipleboxplots" class="nav-link" data-scroll-target="#multipleboxplots">Drawing multiple boxplots</a></li>
  </ul></li>
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">Scatterplots</a>
  <ul class="collapse">
  <li><a href="#more-elaborate-options" id="toc-more-elaborate-options" class="nav-link" data-scroll-target="#more-elaborate-options">More elaborate options</a></li>
  </ul></li>
  <li><a href="#bargraph" id="toc-bargraph" class="nav-link" data-scroll-target="#bargraph">Bar graphs</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Visualisation</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Gordon Wright &amp; Professor Danielle Navarro </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>This material started out as a chapter in the ground-breaking “Learning Statistics with R” by the legendary Danielle Navarro https://learningstatisticswithr.com/ and we will be drawing upon it extensively in the future. This content is remixed from chapter 6 - Drawing Graphs by Dr.&nbsp;Gordon Wright, and is primarily edited down to remove some excellent content that didn’t initially fit with the story I’m telling in the lecture hall and to use some data that are more familiar to us at Goldsmiths after last week. It will make a return at a later date. Thanks for leading the way, Dani!</p>
<p>This material is published under a Creative Commons BY-SA license (CC BY-SA) version 4.0. This means that this book can be reused, remixed, retained, revised and redistributed (including commercially) as long as appropriate credit is given to the authors. If you remix, or modify the original version of this open textbook, you must redistribute all versions of this open textbook under the same license - CC BY-SA. https://creativecommons.org/licenses/by-sa/4.0/</p>
</div>
</div>
</div>
<section id="graphics" class="level1">
<h1>Drawing graphs</h1>
<blockquote class="blockquote">
<p><em>Above all else show the data.</em></p>
<p>–Edward Tufte<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</blockquote>
<p>Visualising data is one of the most important tasks facing the data analyst. It’s important for two distinct but closely related reasons. Firstly, there’s the matter of drawing “presentation graphics”: displaying your data in a clean, visually appealing fashion makes it easier for your reader to understand what you’re trying to tell them. Equally important, perhaps even more important, is the fact that drawing graphs helps <em>you</em> to understand the data. To that end, it’s important to draw “exploratory graphics” that help you learn about the data as you go about analysing it. These points might seem pretty obvious, but I cannot count the number of times I’ve seen people forget them.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/snowmap1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A stylised redrawing of John Snow’s original cholera map. Each small dot represents the location of a cholera case, and each large circle shows the location of a well. As the plot makes clear, the cholera outbreak is centred very closely on the Broad St pump. This image uses the data from the <code>HistData</code> package, and was drawn using minor alterations to the commands provided in the help files. Note that Snow’s original hand drawn map used different symbols and labels, but you get the idea.</figcaption>
</figure>
</div>
</div>
</div>
<p>To give a sense of the importance of this chapter, I want to start with a classic illustration of just how powerful a good graph can be. To that end, Figure @ref(fig:snowmap1) shows a redrawing of one of the most famous data visualisations of all time: John Snow’s 1854 map of cholera deaths. The map is elegant in its simplicity. In the background we have a street map, which helps orient the viewer. Over the top, we see a large number of small dots, each one representing the location of a cholera case. The larger symbols show the location of water pumps, labelled by name. Even the most casual inspection of the graph makes it very clear that the source of the outbreak is almost certainly the Broad Street pump. Upon viewing this graph, Dr Snow arranged to have the handle removed from the pump, ending the outbreak that had killed over 500 people. Such is the power of a good data visualisation. We saw this in the lecture in week 02, but this Guardian Data Blog is very good and features the original https://www.theguardian.com/news/datablog/2013/mar/15/john-snow-cholera-map.</p>
<section id="introplotting" class="level2">
<h2 class="anchored" data-anchor-id="introplotting">An introduction to plotting</h2>
<p>Before I discuss any specialised graphics, let’s start by drawing a few very simple graphs just to get a feel for what it’s like to draw pictures using R. To that end, let’s create a small vector <code>Fibonacci</code> that contains a few numbers we’d like R to draw for us. Then, we’ll ask R to <code>plot()</code> those numbers. The result is Figure @ref(fig:firstplot).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>Fibonacci <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">13</span> )</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">plot</span>( Fibonacci )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/firstplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Our first plot</figcaption>
</figure>
</div>
</div>
</div>
<p>As you can see, what R has done is plot the <em>values</em> stored in the <code>Fibonacci</code> variable on the vertical axis (y-axis) and the corresponding <em>index</em> on the horizontal axis (x-axis). In other words, since the 4th element of the vector has a value of 3, we get a dot plotted at the location (4,3). That’s pretty straightforward, and the image in Figure @ref(fig:firstplot) is probably pretty close to what you would have had in mind when I suggested that we plot the <code>Fibonacci</code> data. However, there’s quite a lot of customisation options available to you, so we should probably spend a bit of time looking at some of those options. So, be warned: this ends up being a fairly long section, because there’s so many possibilities open to you. Don’t let it overwhelm you though… while all of the options discussed here are handy to know about, you can get by just fine only knowing a few of them. The only reason I’ve included all this stuff right at the beginning is that it ends up making the rest of the chapter a lot more readable!</p>
<section id="a-tedious-digression" class="level3">
<h3 class="anchored" data-anchor-id="a-tedious-digression">A tedious digression</h3>
<p>Before we go into any discussion of customising plots, we need a little more background. The important thing to note when using the <code>plot()</code> function, is that it’s another example of a <em>generic</em> function (Section @ref(generics), much like <code>print()</code> and <code>summary()</code>, and so its behaviour changes depending on what kind of input you give it. However, the <code>plot()</code> function is somewhat fancier than the other two, and its behaviour depends on <em>two</em> arguments, <code>x</code> (the first input, which is required) and <code>y</code> (which is optional). This makes it (a) extremely powerful once you get the hang of it, and (b) hilariously unpredictable, when you’re not sure what you’re doing. As much as possible, I’ll try to make clear what type of inputs produce what kinds of outputs. For now, however, it’s enough to note that I’m only doing very basic plotting, and as a consequence all of the work is being done by the <code>plot.default()</code> function.</p>
<p>What kinds of customisations might we be interested in? If you look at the help documentation for the default plotting method (i.e., type <code>?plot.default</code> or <code>help("plot.default")</code>) you’ll see a very long list of arguments that you can specify to customise your plot. I’ll talk about several of them in a moment, but first I want to point out something that might seem quite wacky. When you look at all the different options that the help file talks about, you’ll notice that <em>some</em> of the options that it refers to are “proper” arguments to the <code>plot.default()</code> function, but it also goes on to mention a bunch of things that <em>look</em> like they’re supposed to be arguments, but they’re not listed in the “Usage” section of the file, and the documentation calls them <strong><em>graphical parameters</em></strong> instead. Even so, it’s usually possible to treat them as if they were arguments of the plotting function. Very odd. In order to stop my readers trying to find a brick and look up my home address, I’d better explain what’s going on; or at least give the basic gist behind it.</p>
<p>What exactly is a graphical parameter? Basically, the idea is that there are some characteristics of a plot which are pretty universal: for instance, regardless of what kind of graph you’re drawing, you probably need to specify what colour to use for the plot, right? So you’d expect there to be something like a <code>col</code> argument to every single graphics function in R? Well, sort of. In order to avoid having hundreds of arguments for every single function, what R does is refer to a bunch of these “graphical parameters” which are pretty general purpose. Graphical parameters can be changed directly by using the low-level <code>par()</code> function, which I discuss briefly in Section @ref(par) though not in a lot of detail. If you look at the help files for graphical parameters (i.e., type <code>?par</code>) you’ll see that there’s <em>lots</em> of them. Fortunately, (a) the default settings are generally pretty good so you can ignore the majority of the parameters, and (b) as you’ll see as we go through this chapter, you very rarely need to use <code>par()</code> directly, because you can “pretend” that graphical parameters are just additional arguments to your high-level function (e.g.&nbsp;<code>plot.default()</code>). In short… yes, R does have these wacky “graphical parameters” which can be quite confusing. But in most basic uses of the plotting functions, you can act as if they were just undocumented additional arguments to your function.</p>
</section>
<section id="figtitles" class="level3">
<h3 class="anchored" data-anchor-id="figtitles">Customising the title and the axis labels</h3>
<p>One of the first things that you’ll find yourself wanting to do when customising your plot is to label it better. You might want to specify more appropriate axis labels, add a title or add a subtitle. The arguments that you need to specify to make this happen are:</p>
<ul>
<li><code>main</code>. A character string containing the title.</li>
<li><code>sub</code>. A character string containing the subtitle.</li>
<li><code>xlab</code>. A character string containing the x-axis label.</li>
<li><code>ylab</code>. A character string containing the y-axis label.</li>
</ul>
<p>These aren’t graphical parameters, they’re arguments to the high-level function. However, because the high-level functions all rely on the same low-level function to do the drawing<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> the names of these arguments are identical for pretty much every high-level function I’ve come across. Let’s have a look at what happens when we make use of all these arguments. Here’s the command. The picture that this draws is shown in Figure @ref(fig:secondplot).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">plot</span>( <span class="at">x =</span> Fibonacci,</span>
<span id="cb2-2"><a href="#cb2-2"></a>               <span class="at">main =</span> <span class="st">"You specify title using the 'main' argument"</span>,</span>
<span id="cb2-3"><a href="#cb2-3"></a>               <span class="at">sub =</span> <span class="st">"The subtitle appears here! (Use the 'sub' argument for this)"</span>,</span>
<span id="cb2-4"><a href="#cb2-4"></a>               <span class="at">xlab =</span> <span class="st">"The x-axis label is 'xlab'"</span>,</span>
<span id="cb2-5"><a href="#cb2-5"></a>                <span class="at">ylab =</span> <span class="st">"The y-axis label is 'ylab'"</span> </span>
<span id="cb2-6"><a href="#cb2-6"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/secondplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>How to add your own title, subtitle, x-axis label and y-axis label to the plot.</figcaption>
</figure>
</div>
</div>
</div>
<p>It’s more or less as you’d expect. The plot itself is identical to the one we drew in Figure @ref(fig:firstplot), except for the fact that we’ve changed the axis labels, and added a title and a subtitle. Even so, there’s a couple of interesting features worth calling your attention to. Firstly, notice that the subtitle is drawn below the plot, which I personally find annoying; as a consequence I almost never use subtitles. You may have a different opinion, of course, but the important thing is that you remember where the subtitle actually goes. Secondly, notice that R has decided to use boldface text and a larger font size for the title. This is one of my most hated default settings in R graphics, since I feel that it draws too much attention to the title. Generally, while I do want my reader to look at the title, I find that the R defaults are a bit overpowering, so I often like to change the settings. To that end, there are a bunch of graphical parameters that you can use to customise the font style:</p>
<ul>
<li><em>Font styles:</em> <code>font.main</code>, <code>font.sub</code>, <code>font.lab</code>, <code>font.axis</code>. These four parameters control the font style used for the plot title (<code>font.main</code>), the subtitle (<code>font.sub</code>), the axis labels (<code>font.lab</code>: note that you can’t specify separate styles for the x-axis and y-axis without using low level commands), and the numbers next to the tick marks on the axis (<code>font.axis</code>). Somewhat irritatingly, these arguments are numbers instead of meaningful names: a value of 1 corresponds to plain text, 2 means boldface, 3 means italic and 4 means bold italic.</li>
<li><em>Font colours:</em> <code>col.main</code>, <code>col.sub</code>, <code>col.lab</code>, <code>col.axis</code>. These parameters do pretty much what the name says: each one specifies a <strong>col</strong>our in which to type each of the different bits of text. Conveniently, R has a very large number of named colours (type <code>colours()</code> to see a list of over 650 colour names that R knows), so you can use the English language name of the colour to select it.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Thus, the parameter value here string like <code>"red"</code>, <code>"gray25"</code> or <code>"springgreen4"</code> (yes, R really does recognise four different shades of “spring green”).</li>
<li><em>Font size:</em> <code>cex.main</code>, <code>cex.sub</code>, <code>cex.lab</code>, <code>cex.axis</code>. Font size is handled in a slightly curious way in R. The “cex” part here is short for “<strong>c</strong>haracter <strong>ex</strong>pansion”, and it’s essentially a magnification value. By default, all of these are set to a value of 1, except for the font title: <code>cex.main</code> has a default magnification of 1.2, which is why the title font is 20% bigger than the others.</li>
<li><em>Font family:</em> <code>family</code>. This argument specifies a font family to use: the simplest way to use it is to set it to <code>"sans"</code>, <code>"serif"</code>, or <code>"mono"</code>, corresponding to a san serif font, a serif font, or a monospaced font. If you want to, you can give the name of a specific font, but keep in mind that different operating systems use different fonts, so it’s probably safest to keep it simple. Better yet, unless you have some deep objections to the R defaults, just ignore this parameter entirely. That’s what I usually do.</li>
</ul>
<p>To give you a sense of how you can use these parameters to customise your titles, the following command can be used to draw Figure @ref(fig:thirdplot):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">plot</span>( <span class="at">x =</span> Fibonacci,                           <span class="co"># the data to plot</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>          <span class="at">main =</span> <span class="st">"The first 7 Fibonacci numbers"</span>,  <span class="co"># the title</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>          <span class="at">xlab =</span> <span class="st">"Position in the sequence"</span>,       <span class="co"># x-axis label</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>          <span class="at">ylab =</span> <span class="st">"The Fibonacci number"</span>,           <span class="co"># y-axis </span></span>
<span id="cb3-5"><a href="#cb3-5"></a>          <span class="at">font.main =</span> <span class="dv">1</span>,</span>
<span id="cb3-6"><a href="#cb3-6"></a>          <span class="at">cex.main =</span> <span class="dv">1</span>,</span>
<span id="cb3-7"><a href="#cb3-7"></a>          <span class="at">font.axis =</span> <span class="dv">2</span>,</span>
<span id="cb3-8"><a href="#cb3-8"></a>          <span class="at">col.lab =</span> <span class="st">"gray50"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/thirdplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>How to customise the appearance of the titles and labels.</figcaption>
</figure>
</div>
</div>
</div>
<p>Although this command is quite long, it’s not complicated: all it does is override a bunch of the default parameter values. The only difficult aspect to this is that you have to remember what each of these parameters is called, and what all the different values are. And in practice I never remember: I have to look up the help documentation every time, or else look it up in this book.</p>
</section>
<section id="changing-the-plot-type" class="level3">
<h3 class="anchored" data-anchor-id="changing-the-plot-type">Changing the plot type</h3>
<p>Adding and customising the titles associated with the plot is one way in which you can play around with what your picture looks like. Another thing that you’ll want to do is customise the appearance of the actual plot! To start with, let’s look at the single most important options that the <code>plot()</code> function (or, recalling that we’re dealing with a generic function, in this case the <code>plot.default()</code> function, since that’s the one doing all the work) provides for you to use, which is the <code>type</code> argument. The type argument specifies the visual style of the plot. The possible values for this are:</p>
<ul>
<li><code>type = "p"</code>. Draw the <strong>p</strong>oints only.</li>
<li><code>type = "l"</code>. Draw a <strong>l</strong>ine through the points.</li>
<li><code>type = "o"</code>. Draw the line <strong>o</strong>ver the top of the points.</li>
<li><code>type = "b"</code>. Draw <strong>b</strong>oth points and lines, but don’t overplot.</li>
<li><code>type = "h"</code>. Draw “<strong>h</strong>istogram-like” vertical bars.</li>
<li><code>type = "s"</code>. Draw a <strong>s</strong>taircase, going horizontally then vertically.</li>
<li><code>type = "S"</code>. Draw a <strong>S</strong>taircase, going vertically then horizontally.</li>
<li><code>type = "c"</code>. Draw only the <strong>c</strong>onnecting lines from the “b” version.</li>
<li><code>type = "n"</code>. Draw nothing. (Apparently this is useful sometimes?)</li>
</ul>
<p>The simplest way to illustrate what each of these really looks like is just to draw them. To that end, Figure @ref(fig:simpleplots) shows the same Fibonacci data, drawn using six different <code>types</code> of plot. As you can see, by altering the type argument you can get a qualitatively different appearance to your plot. In other words, as far as R is concerned, the only difference between a scatterplot (like the ones we drew in Section @ref(correl) and a line plot is that you draw a scatterplot by setting <code>type = "p"</code> and you draw a line plot by setting <code>type = "l"</code>. However, that doesn’t imply that <em>you</em> should think of them as begin equivalent to each other. As you can see by looking at Figure @ref(fig:simpleplots), a line plot implies that there is some notion of continuity from one point to the next, whereas a scatterplot does not.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/simpleplots-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Changing the <code>type</code> of the plot.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="changing-other-features-of-the-plot" class="level3">
<h3 class="anchored" data-anchor-id="changing-other-features-of-the-plot">Changing other features of the plot</h3>
<p>In Section @ref(figtitles) we talked about a group of graphical parameters that are related to the formatting of titles, axis labels etc. The second group of parameters I want to discuss are those related to the formatting of the plot itself:</p>
<ul>
<li><em>Colour of the plot</em>: <code>col</code>. As we saw with the previous colour-related parameters, the simplest way to specify this parameter is using a character string: e.g., <code>col = "blue"</code>. It’s a pretty straightforward parameter to specify: the only real subtlety is that every high-level function tends to draw a different “thing” as it’s output, and so this parameter gets interpreted a little differently by different functions. However, for the <code>plot.default()</code> function it’s pretty simple: the <code>col</code> argument refers to the colour of the points and/or lines that get drawn!</li>
<li><em>Character used to plot points</em>: <code>pch</code>. The <strong>p</strong>lot <strong>ch</strong>aracter parameter is a number, usually between 1 and 25. What it does is tell R what symbol to use to draw the points that it plots. The simplest way to illustrate what the different values do is with a picture. Figure @ref(fig:pch) shows the first 25 plotting characters. The default plotting character is a hollow circle (i.e., <code>pch = 1</code>).</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/pch-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Changing the plotted characters</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><em>Plot size</em>: <code>cex</code>. This parameter describes a <strong>c</strong>haracter <strong>ex</strong>pansion factor (i.e., magnification) for the plotted characters. By default <code>cex=1</code>, but if you want bigger symbols in your graph you should specify a larger value.</li>
<li><em>Line type</em>: <code>lty</code>. The <strong>l</strong>ine <strong>ty</strong>pe parameter describes the kind of line that R draws. It has seven values which you can specify using a number between <code>0</code> and <code>7</code>, or using a meaningful character string: <code>"blank"</code>, <code>"solid"</code>, <code>"dashed"</code>, <code>"dotted"</code>, <code>"dotdash"</code>, <code>"longdash"</code>, or <code>"twodash"</code>. Note that the “blank” version (value 0) just means that R doesn’t draw the lines at all. The other six versions are shown in Figure @ref(fig:lty).</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/lty-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Line types</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><em>Line width</em>: <code>lwd</code>. The last graphical parameter in this category that I want to mention is the <strong>l</strong>ine <strong>w</strong>i<strong>d</strong>th parameter, which is just a number specifying the width of the line. The default value is 1. Not surprisingly, larger values produce thicker lines and smaller values produce thinner lines. Try playing around with different values of <code>lwd</code> to see what happens.</li>
</ul>
<p>To illustrate what you can do by altering these parameters, let’s try the following command, the output is shown in Figure @ref(fig:fifthplot).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">plot</span>( <span class="at">x =</span> Fibonacci,</span>
<span id="cb4-2"><a href="#cb4-2"></a>         <span class="at">type =</span> <span class="st">"b"</span>,</span>
<span id="cb4-3"><a href="#cb4-3"></a>         <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb4-4"><a href="#cb4-4"></a>         <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb4-5"><a href="#cb4-5"></a>         <span class="at">cex=</span><span class="dv">5</span>,</span>
<span id="cb4-6"><a href="#cb4-6"></a>         <span class="at">lty=</span><span class="dv">2</span>,</span>
<span id="cb4-7"><a href="#cb4-7"></a>         <span class="at">lwd=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/fifthplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Customising various aspects to the plot itself.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="changing-the-appearance-of-the-axes" class="level3">
<h3 class="anchored" data-anchor-id="changing-the-appearance-of-the-axes">Changing the appearance of the axes</h3>
<p>There are several other possibilities worth discussing. Ignoring graphical parameters for the moment, there’s a few other arguments to the <code>plot.default()</code> function that you might want to use. As before, many of these are standard arguments that are used by a lot of high level graphics functions:</p>
<ul>
<li><em>Changing the axis scales</em>: <code>xlim</code>, <code>ylim</code>. Generally R does a pretty good job of figuring out where to set the edges of the plot. However, you can override its choices by setting the <code>xlim</code> and <code>ylim</code> arguments. For instance, if I decide I want the vertical scale of the plot to run from 0 to 100, then I’d set <code>ylim = c(0, 100)</code>.</li>
<li><em>Suppress labelling</em>: <code>ann</code>. This is a logical-valued argument that you can use if you don’t want R to include any text for a title, subtitle or axis label. To do so, set <code>ann = FALSE</code>. This will stop R from including any text that would normally appear in those places. Note that this will override any of your manual titles. For example, if you try to add a title using the <code>main</code> argument, but you also specify <code>ann = FALSE</code>, no title will appear.</li>
<li><em>Suppress axis drawing</em>: <code>axes</code>. Again, this is a logical valued argument. Suppose you don’t want R to draw any axes at all. To suppress the axes, all you have to do is add <code>axes = FALSE</code>. This will remove the axes and the numbering, but not the axis labels (i.e.&nbsp;the <code>xlab</code> and <code>ylab</code> text). Note that you can get finer grain control over this by specifying the <code>xaxt</code> and <code>yaxt</code> graphical parameters instead (see below).</li>
<li><em>Include a framing box</em>: <code>frame.plot</code>. Suppose you’ve removed the axes by setting <code>axes = FALSE</code>, but you still want to have a simple box drawn around the plot; that is, you only wanted to get rid of the numbering and the tick marks, but you want to keep the box. To do that, you set <code>frame.plot = TRUE</code>.</li>
</ul>
<p>Note that this list isn’t exhaustive. There are a few other arguments to the <code>plot.default</code> function that you can play with if you want to, but those are the ones you are probably most likely to want to use. As always, however, if these aren’t enough options for you, there’s also a number of other graphical parameters that you might want to play with as well. That’s the focus of the next section. In the meantime, here’s a command that makes use of all these different options. The output is shown in Figure @ref(fig:fourthplot), and it’s pretty much exactly as you’d expect. The axis scales on both the horizontal and vertical dimensions have been expanded, the axes have been suppressed as have the annotations, but I’ve kept a box around the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">plot</span>( <span class="at">x =</span> Fibonacci,       <span class="co"># the data</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>),     <span class="co"># expand the x-scale</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>),     <span class="co"># expand the y-scale</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>       <span class="at">ann =</span> <span class="cn">FALSE</span>,         <span class="co"># delete all annotations</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>       <span class="at">axes =</span> <span class="cn">FALSE</span>,        <span class="co"># delete the axes</span></span>
<span id="cb5-6"><a href="#cb5-6"></a>       <span class="at">frame.plot =</span> <span class="cn">TRUE</span>    <span class="co"># but include a framing box</span></span>
<span id="cb5-7"><a href="#cb5-7"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/fourthplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Altering the scale and appearance of the plot axes.</figcaption>
</figure>
</div>
</div>
</div>
<p>Before moving on, I should point out that there are several graphical parameters relating to the axes, the box, and the general appearance of the plot which allow finer grain control over the appearance of the axes and the annotations.</p>
<ul>
<li><em>Suppressing the axes individually</em>: <code>xaxt</code>, <code>yaxt</code>. These graphical parameters are basically just fancier versions of the <code>axes</code> argument we discussed earlier. If you want to stop R from drawing the vertical axis but you’d like it to keep the horizontal axis, set <code>yaxt = "n"</code>. I trust that you can figure out how to keep the vertical axis and suppress the horizontal one!</li>
<li><em>Box type</em>: <code>bty</code>. In the same way that <code>xaxt</code>, <code>yaxt</code> are just fancy versions of <code>axes</code>, the <strong>b</strong>ox <strong>ty</strong>pe parameter is really just a fancier version of the <code>frame.plot</code> argument, allowing you to specify exactly which out of the four borders you want to keep. The way we specify this parameter is a bit stupid, in my opinion: the possible values are <code>"o"</code> (the default), <code>"l"</code>, <code>"7"</code>, <code>"c"</code>, <code>"u"</code>, or <code>"]"</code>, each of which will draw only those edges that the corresponding character suggests. That is, the letter <code>"c"</code> has a top, a bottom and a left, but is blank on the right hand side, whereas <code>"7"</code> has a top and a right, but is blank on the left and the bottom. Alternatively a value of <code>"n"</code> means that no box will be drawn.</li>
<li><em>Orientation of the axis labels</em> <code>las</code>. I presume that the name of this parameter is an acronym of <strong>la</strong>bel <strong>s</strong>tyle or something along those lines; but what it actually does is govern the orientation of the text used to label the individual tick marks (i.e., the numbering, not the <code>xlab</code> and <code>ylab</code> axis labels). There are four possible values for <code>las</code>: A value of 0 means that the labels of both axes are printed parallel to the axis itself (the default). A value of 1 means that the text is always horizontal. A value of 2 means that the labelling text is printed at right angles to the axis. Finally, a value of 3 means that the text is always vertical.</li>
</ul>
<p>Again, these aren’t the only possibilities. There are a few other graphical parameters that I haven’t mentioned that you could use to customise the appearance of the axes,<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> but that’s probably enough (or more than enough) for now. To give a sense of how you could use these parameters, let’s try the following command. The output is shown in Figure @ref(fig:sixthplot). As you can see, this isn’t a very useful plot at all. However, it does illustrate the graphical parameters we’re talking about, so I suppose it serves its purpose.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>    <span class="fu">plot</span>( <span class="at">x =</span> Fibonacci, <span class="co"># the data</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>         <span class="at">xaxt =</span> <span class="st">"n"</span>,       <span class="co"># don't draw the x-axis  </span></span>
<span id="cb6-3"><a href="#cb6-3"></a>         <span class="at">bty =</span> <span class="st">"]"</span>,        <span class="co"># keep bottom, right and top of box only</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>         <span class="at">las =</span> <span class="dv">1</span> )         <span class="co"># rotate the text</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/sixthplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Other ways to customise the axes</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="dont-panic" class="level3">
<h3 class="anchored" data-anchor-id="dont-panic">Don’t panic</h3>
<p>At this point, a lot of readers will be probably be thinking something along the lines of, “if there’s this much detail just for drawing a simple plot, how horrible is it going to get when we start looking at more complicated things?” Perhaps, contrary to my earlier pleas for mercy, you’ve found a brick to hurl and are right now leafing through an Adelaide phone book trying to find my address. Well, fear not! And please, put the brick down. In a lot of ways, we’ve gone through the hardest part: we’ve already covered vast majority of the plot customisations that you might want to do. As you’ll see, each of the other high level plotting commands we’ll talk about will only have a smallish number of additional options. Better yet, even though I’ve told you about a billion different ways of tweaking your plot, you don’t usually need them. So in practice, now that you’ve read over it once to get the gist, the majority of the content of this section is stuff you can safely forget: just remember to come back to this section later on when you want to tweak your plot.</p>
</section>
</section>
<section id="hist" class="level2">
<h2 class="anchored" data-anchor-id="hist">Histograms</h2>
<p>Now that we’ve tamed (or possibly fled from) the beast that is R graphical parameters, let’s talk more seriously about some real life graphics that you’ll want to draw. We begin with the humble <strong><em>histogram</em></strong>. Histograms are one of the simplest and most useful ways of visualising data. They make most sense when you have an interval or ratio scale (e.g., the <code>afl.margins</code> data from Chapter @ref(descriptives) and what you want to do is get an overall impression of the data. Most of you probably know how histograms work, since they’re so widely used, but for the sake of completeness I’ll describe them. All you do is divide up the possible values into <strong><em>bins</em></strong>, and then count the number of observations that fall within each bin. This count is referred to as the frequency of the bin, and is displayed as a bar: in the AFL winning margins data, there are 33 games in which the winning margin was less than 10 points, and it is this fact that is represented by the height of the leftmost bar in Figure @ref(fig:hist1a). Drawing this histogram in R is pretty straightforward. The function you need to use is called <code>hist()</code>, and it has pretty reasonable default settings. In fact, Figure @ref(fig:hist1a) is exactly what you get if you just type this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">hist</span>( afl.margins )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/hist1a-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The default histogram that R produces</figcaption>
</figure>
</div>
</div>
</div>
<p>Although this image would need a lot of cleaning up in order to make a good presentation graphic (i.e., one you’d include in a report), it nevertheless does a pretty good job of describing the data. In fact, the big strength of a histogram is that (properly used) it does show the entire spread of the data, so you can get a pretty good sense about what it looks like. The downside to histograms is that they aren’t very compact: unlike some of the other plots I’ll talk about it’s hard to cram 20-30 histograms into a single image without overwhelming the viewer. And of course, if your data are nominal scale (e.g., the <code>afl.finalists</code> data) then histograms are useless.</p>
<p>The main subtlety that you need to be aware of when drawing histograms is determining where the <code>breaks</code> that separate bins should be located, and (relatedly) how many breaks there should be. In Figure @ref(fig:hist1a), you can see that R has made pretty sensible choices all by itself: the breaks are located at 0, 10, 20, … 120, which is exactly what I would have done had I been forced to make a choice myself. On the other hand, consider the two histograms in Figure @ref(fig:hist1b) and @ref(fig:hist1c), which I produced using the following two commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">hist</span>( <span class="at">x =</span> afl.margins, <span class="at">breaks =</span> <span class="dv">3</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/hist1b-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A histogram with too few bins</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">hist</span>( <span class="at">x =</span> afl.margins, <span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">116</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/hist1c-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A histogram with too many bins</figcaption>
</figure>
</div>
</div>
</div>
<p>In Figure @ref(fig:hist1c), the bins are only 1 point wide. As a result, although the plot is very informative (it displays the entire data set with no loss of information at all!) the plot is very hard to interpret, and feels quite cluttered. On the other hand, the plot in Figure @ref(fig:hist1b) has a bin width of 50 points, and has the opposite problem: it’s very easy to “read” this plot, but it doesn’t convey a lot of information. One gets the sense that this histogram is hiding too much. In short, the way in which you specify the breaks has a big effect on what the histogram looks like, so it’s important to make sure you choose the breaks sensibly. In general R does a pretty good job of selecting the breaks on its own, since it makes use of some quite clever tricks that statisticians have devised for automatically selecting the right bins for a histogram, but nevertheless it’s usually a good idea to play around with the breaks a bit to see what happens.</p>
<p>There is one fairly important thing to add regarding how the <code>breaks</code> argument works. There are two different ways you can specify the breaks. You can either specify <em>how many</em> breaks you want (which is what I did for panel b when I typed <code>breaks = 3</code>) and let R figure out where they should go, or you can provide a vector that tells R exactly where the breaks should be placed (which is what I did for panel c when I typed <code>breaks = 0:116</code>). The behaviour of the <code>hist()</code> function is slightly different depending on which version you use. If all you do is tell it <em>how many</em> breaks you want, R treats it as a “suggestion” not as a demand. It assumes you want “approximately 3” breaks, but if it doesn’t think that this would look very pretty on screen, it picks a different (but similar) number. It does this for a sensible reason – it tries to make sure that the breaks are located at sensible values (like 10) rather than stupid ones (like 7.224414). And most of the time R is right: usually, when a human researcher says “give me 3 breaks”, he or she really does mean “give me approximately 3 breaks, and don’t put them in stupid places”. However, sometimes R is dead wrong. Sometimes you really do mean “exactly 3 breaks”, and you know precisely where you want them to go. So you need to invoke “real person privilege”, and order R to do what it’s bloody well told. In order to do that, you <em>have</em> to input the full vector that tells R exactly where you want the breaks. If you do that, R will go back to behaving like the nice little obedient calculator that it’s supposed to be.</p>
<section id="visual-style-of-your-histogram" class="level3">
<h3 class="anchored" data-anchor-id="visual-style-of-your-histogram">Visual style of your histogram</h3>
<p>Okay, so at this point we can draw a basic histogram, and we can alter the number and even the location of the <code>breaks</code>. However, the visual style of the histograms shown in Figures @ref(fig:hist1a), @ref(fig:hist1b), and @ref(fig:hist1c) could stand to be improved. We can fix this by making use of some of the other arguments to the <code>hist()</code> function. Most of the things you might want to try doing have already been covered in Section @ref(introplotting), but there’s a few new things:</p>
<ul>
<li><em>Shading lines</em>: <code>density</code>, <code>angle</code>. You can add diagonal lines to shade the bars: the <code>density</code> value is a number indicating how many lines per inch R should draw (the default value of <code>NULL</code> means no lines), and the <code>angle</code> is a number indicating how many degrees from horizontal the lines should be drawn at (default is <code>angle = 45</code> degrees).</li>
<li><em>Specifics regarding colours</em>: <code>col</code>, <code>border</code>. You can also change the colours: in this instance the <code>col</code> parameter sets the colour of the shading (either the shading lines if there are any, or else the colour of the interior of the bars if there are not), and the <code>border</code> argument sets the colour of the edges of the bars.</li>
<li><em>Labelling the bars</em>: <code>labels</code>. You can also attach labels to each of the bars using the <code>labels</code> argument. The simplest way to do this is to set <code>labels = TRUE</code>, in which case R will add a number just above each bar, that number being the exact number of observations in the bin. Alternatively, you can choose the labels yourself, by inputting a vector of strings, e.g., <code>labels = c("label 1","label 2","etc")</code></li>
</ul>
<p>Not surprisingly, this doesn’t exhaust the possibilities. If you type <code>help("hist")</code> or <code>?hist</code> and have a look at the help documentation for histograms, you’ll see a few more options. A histogram that makes use of the histogram-specific customisations as well as several of the options we discussed in Section @ref(introplotting) is shown in Figure @ref(fig:hist1d). The R command that I used to draw it is this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">hist</span>( <span class="at">x =</span> afl.margins, </span>
<span id="cb10-2"><a href="#cb10-2"></a>      <span class="at">main =</span> <span class="st">"2010 AFL margins"</span>, <span class="co"># title of the plot</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>      <span class="at">xlab =</span> <span class="st">"Margin"</span>,           <span class="co"># set the x-axis label</span></span>
<span id="cb10-4"><a href="#cb10-4"></a>      <span class="at">density =</span> <span class="dv">10</span>,              <span class="co"># draw shading lines: 10 per inch</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>      <span class="at">angle =</span> <span class="dv">40</span>,                <span class="co"># set the angle of the shading lines is 40 degrees</span></span>
<span id="cb10-6"><a href="#cb10-6"></a>      <span class="at">border =</span> <span class="st">"gray20"</span>,         <span class="co"># set the colour of the borders of the bars</span></span>
<span id="cb10-7"><a href="#cb10-7"></a>      <span class="at">col =</span> <span class="st">"gray80"</span>,            <span class="co"># set the colour of the shading lines</span></span>
<span id="cb10-8"><a href="#cb10-8"></a>      <span class="at">labels =</span> <span class="cn">TRUE</span>,             <span class="co"># add frequency labels to each bar</span></span>
<span id="cb10-9"><a href="#cb10-9"></a>      <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">40</span>)             <span class="co"># change the scale of the y-axis</span></span>
<span id="cb10-10"><a href="#cb10-10"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/hist1d-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A histogram with histogram specific customisations</figcaption>
</figure>
</div>
</div>
</div>
<p>Overall, this is a much nicer histogram than the default ones.</p>
</section>
</section>
<section id="stem" class="level2">
<h2 class="anchored" data-anchor-id="stem">Stem and leaf plots</h2>
<p>Histograms are one of the most widely used methods for displaying the observed values for a variable. They’re simple, pretty, and very informative. However, they do take a little bit of effort to draw. Sometimes it can be quite useful to make use of simpler, if less visually appealing, options. One such alternative is the <strong><em>stem and leaf plot</em></strong>. To a first approximation you can think of a stem and leaf plot as a kind of text-based histogram. Stem and leaf plots aren’t used as widely these days as they were 30 years ago, since it’s now just as easy to draw a histogram as it is to draw a stem and leaf plot. Not only that, they don’t work very well for larger data sets. As a consequence you probably won’t have as much of a need to use them yourself, though you may run into them in older publications. These days, the only real world situation where I use them is if I have a small data set with 20-30 data points and I don’t have a computer handy, because it’s pretty easy to quickly sketch a stem and leaf plot by hand.</p>
<p>With all that as background, lets have a look at stem and leaf plots. The AFL margins data contains 176 observations, which is at the upper end for what you can realistically plot this way. The function in R for drawing stem and leaf plots is called <code>stem()</code> and if we ask for a stem and leaf plot of the <code>afl.margins</code> data, here’s what we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">stem</span>( afl.margins )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

   0 | 001111223333333344567788888999999
   1 | 0000011122234456666899999
   2 | 00011222333445566667788999999
   3 | 01223555566666678888899
   4 | 012334444477788899
   5 | 00002233445556667
   6 | 0113455678
   7 | 01123556
   8 | 122349
   9 | 458
  10 | 148
  11 | 6</code></pre>
</div>
</div>
<p>The values to the left of the <code>|</code> are called <strong><em>stems</em></strong> and the values to the right are called <strong><em>leaves</em></strong>. If you just look at the shape that the leaves make, you can see something that looks a lot like a histogram made out of numbers, just rotated by 90 degrees. But if you know how to read the plot, there’s quite a lot of additional information here. In fact, it’s also giving you the actual values of <em>all</em> of the observations in the data set. To illustrate, let’s have a look at the last line in the stem and leaf plot, namely <code>11 | 6</code>. Specifically, let’s compare this to the largest values of the <code>afl.margins</code> data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">max</span>( afl.margins )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 116</code></pre>
</div>
</div>
<p>Hm… <code>11 | 6</code> versus <code>116</code>. Obviously the stem and leaf plot is trying to tell us that the largest value in the data set is 116. Similarly, when we look at the line that reads <code>10 | 148</code>, the way we interpret it to note that the stem and leaf plot is telling us that the data set contains observations with values 101, 104 and 108. Finally, when we see something like <code>5 | 00002233445556667</code> the four <code>0</code>s in the the stem and leaf plot are telling us that there are four observations with value 50.</p>
<p>I won’t talk about them in a lot of detail, but I should point out that some customisation options are available for stem and leaf plots in R. The two arguments that you can use to do this are:</p>
<ul>
<li><code>scale</code>. Changing the <code>scale</code> of the plot (default value is 1), which is analogous to changing the number of breaks in a histogram. Reducing the scale causes R to reduce the number of stem values (i.e., the number of breaks, if this were a histogram) that the plot uses.</li>
<li><code>width</code>. The second way that to can customise a stem and leaf plot is to alter the <code>width</code> (default value is 80). Changing the width alters the maximum number of leaf values that can be displayed for any given stem.</li>
</ul>
<p>However, since stem and leaf plots aren’t as important as they used to be, I’ll leave it to the interested reader to investigate these options. Try the following two commands to see what happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">stem</span>( <span class="at">x =</span> afl.margins, <span class="at">scale =</span> .<span class="dv">25</span> )</span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="fu">stem</span>( <span class="at">x =</span> afl.margins, <span class="at">width =</span> <span class="dv">20</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The only other thing to note about stem and leaf plots is the line in which R tells you where the decimal point is. If our data set had included only the numbers .11, .15, .23, .35 and .59 and we’d drawn a stem and leaf plot of these data, then R would move the decimal point: the stem values would be 1,2,3,4 and 5, but R would tell you that the decimal point has moved to the left of the <code>|</code> symbol. If you want to see this in action, try the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">stem</span>( <span class="at">x =</span> afl.margins <span class="sc">/</span> <span class="dv">1000</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The stem and leaf plot itself will look identical to the original one we drew, except for the fact that R will tell you that the decimal point has moved.</p>
</section>
<section id="boxplots" class="level2">
<h2 class="anchored" data-anchor-id="boxplots">Boxplots</h2>
<p>Another alternative to histograms is a <strong><em>boxplot</em></strong>, sometimes called a “box and whiskers” plot. Like histograms, they’re most suited to interval or ratio scale data. The idea behind a boxplot is to provide a simple visual depiction of the median, the interquartile range, and the range of the data. And because they do so in a fairly compact way, boxplots have become a very popular statistical graphic, especially during the exploratory stage of data analysis when you’re trying to understand the data yourself. Let’s have a look at how they work, again using the <code>afl.margins</code> data as our example. Firstly, let’s actually calculate these numbers ourselves using the <code>summary()</code> function:<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">summary</span>( afl.margins )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   12.75   30.50   35.30   50.50  116.00 </code></pre>
</div>
</div>
<p>So how does a boxplot capture these numbers? The easiest way to describe what a boxplot looks like is just to draw one. The function for doing this in R is (surprise, surprise) <code>boxplot()</code>. As always there’s a lot of optional arguments that you can specify if you want, but for the most part you can just let R choose the defaults for you. That said, I’m going to override one of the defaults to start with by specifying the <code>range</code> option, but for the most part you won’t want to do this (I’ll explain why in a minute). With that as preamble, let’s try the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">boxplot</span>( <span class="at">x =</span> afl.margins, <span class="at">range =</span> <span class="dv">100</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/boxplot1a-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A basic boxplot</figcaption>
</figure>
</div>
</div>
</div>
<p>What R draws is shown in Figure @ref(fig:boxplot1a), the most basic boxplot possible. When you look at this plot, this is how you should interpret it: the thick line in the middle of the box is the median; the box itself spans the range from the 25th percentile to the 75th percentile; and the “whiskers” cover the full range from the minimum value to the maximum value. This is summarised in the annotated plot in Figure @ref(fig:boxplot1b).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="materials/images/boxplot1_annotated.png" class="img-fluid figure-img"></p>
<figcaption>An annotated boxplot</figcaption>
</figure>
</div>
</div>
</div>
<p>In practice, this isn’t quite how boxplots usually work. In most applications, the “whiskers” don’t cover the full range from minimum to maximum. Instead, they actually go out to the most extreme data point that doesn’t exceed a certain bound. By default, this value is 1.5 times the interquartile range, corresponding to a <code>range</code> value of 1.5. Any observation whose value falls outside this range is plotted as a circle instead of being covered by the whiskers, and is commonly referred to as an <strong><em>outlier</em></strong>. For our AFL margins data, there is one observation (a game with a margin of 116 points) that falls outside this range. As a consequence, the upper whisker is pulled back to the next largest observation (a value of 108), and the observation at 116 is plotted as a circle. This is illustrated in Figure @ref(fig:boxplot2a). Since the default value is <code>range = 1.5</code> we can draw this plot using the simple command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">boxplot</span>( afl.margins )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/boxplot2a-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>By default, R will only extent the whiskers a distance of 1.5 times the interquartile range, and will plot any points that fall outside that range separately</figcaption>
</figure>
</div>
</div>
</div>
<section id="visual-style-of-your-boxplot" class="level3">
<h3 class="anchored" data-anchor-id="visual-style-of-your-boxplot">Visual style of your boxplot</h3>
<p>I’ll talk a little more about the relationship between boxplots and outliers in the Section @ref(boxplotoutliers), but before I do let’s take the time to clean this figure up. Boxplots in R are extremely customisable. In addition to the usual range of graphical parameters that you can tweak to make the plot look nice, you can also exercise nearly complete control over every element to the plot. Consider the boxplot in Figure @ref(fig:boxplot2b): in this version of the plot, not only have I added labels (<code>xlab</code>, <code>ylab</code>) and removed the stupid border (<code>frame.plot</code>), I’ve also dimmed all of the graphical elements of the boxplot except the central bar that plots the median (<code>border</code>) so as to draw more attention to the median rather than the rest of the boxplot.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/boxplot2b-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A boxplot with boxplot specific customisations</figcaption>
</figure>
</div>
</div>
</div>
<p>You’ve seen all these options in previous sections in this chapter, so hopefully those customisations won’t need any further explanation. However, I’ve done two new things as well: I’ve deleted the cross-bars at the top and bottom of the whiskers (known as the “staples” of the plot), and converted the whiskers themselves to solid lines. The arguments that I used to do this are called by the ridiculous names of <code>staplewex</code> and <code>whisklty</code>,<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> and I’ll explain these in a moment.</p>
<p>But first, here’s the actual command I used to draw this figure:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">boxplot</span>( <span class="at">x =</span> afl.margins,           <span class="co"># the data</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>          <span class="at">xlab =</span> <span class="st">"AFL games, 2010"</span>,  <span class="co"># x-axis label</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>          <span class="at">ylab =</span> <span class="st">"Winning Margin"</span>,   <span class="co"># y-axis label</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>          <span class="at">border =</span> <span class="st">"grey50"</span>,         <span class="co"># dim the border of the box</span></span>
<span id="cb21-5"><a href="#cb21-5"></a>          <span class="at">frame.plot =</span> <span class="cn">FALSE</span>,        <span class="co"># don't draw a frame</span></span>
<span id="cb21-6"><a href="#cb21-6"></a>          <span class="at">staplewex =</span> <span class="dv">0</span>,             <span class="co"># don't draw staples</span></span>
<span id="cb21-7"><a href="#cb21-7"></a>          <span class="at">whisklty =</span> <span class="dv">1</span>               <span class="co"># solid line for whisker </span></span>
<span id="cb21-8"><a href="#cb21-8"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Overall, I think the resulting boxplot is a huge improvement in visual design over the default version. In my opinion at least, there’s a fairly minimalist aesthetic that governs good statistical graphics. Ideally, every visual element that you add to a plot should convey part of the message. If your plot includes things that don’t actually help the reader learn anything new, you should consider removing them. Personally, I can’t see the point of the cross-bars on a standard boxplot, so I’ve deleted them.</p>
<p>Okay, what commands can we use to customise the boxplot? If you type <code>?boxplot</code> and flick through the help documentation, you’ll notice that it does mention <code>staplewex</code> as an argument, but there’s no mention of <code>whisklty</code>. The reason for this is that the function that handles the drawing is called <code>bxp()</code>, so if you type <code>?bxp</code> all the gory details appear. Here’s the short summary. In order to understand why these arguments have such stupid names, you need to recognise that they’re put together from two components. The first part of the argument name specifies one part of the box plot: <code>staple</code> refers to the staples of the plot (i.e., the cross-bars), and <code>whisk</code> refers to the whiskers. The second part of the name specifies a graphical parameter: <code>wex</code> is a width parameter, and <code>lty</code> is a line type parameter. The parts of the plot you can customise are:</p>
<ul>
<li><code>box</code>. The box that covers the interquartile range.</li>
<li><code>med</code>. The line used to show the median.</li>
<li><code>whisk</code>. The vertical lines used to draw the whiskers.</li>
<li><code>staple</code>. The cross bars at the ends of the whiskers.</li>
<li><code>out</code>. The points used to show the outliers.</li>
</ul>
<p>The actual graphical parameters that you might want to specify are slightly different for each visual element, just because they’re different shapes from each other. As a consequence, the following options are available:</p>
<ul>
<li><em>Width expansion:</em> <code>boxwex, staplewex, outwex</code>. These are scaling factors that govern the width of various parts of the plot. The default scaling factor is (usually) 0.8 for the box, and 0.5 for the other two. Note that in the case of the outliers this parameter is meaningless unless you decide to draw lines plotting the outliers rather than use points.</li>
<li><em>Line type:</em> <code>boxlty, medlty, whisklty, staplelty, outlty</code>. These govern the line type for the relevant elements. The values for this are exactly the same as those used for the regular <code>lty</code> parameter, with two exceptions. There’s an additional option where you can set <code>medlty = "blank"</code> to suppress the median line completely (useful if you want to draw a point for the median rather than plot a line). Similarly, by default the outlier line type is set to <code>outlty = "blank"</code>, because the default behaviour is to draw outliers as points instead of lines.</li>
<li><em>Line width:</em> <code>boxlwd, medlwd, whisklwd, staplelwd, outlwd</code>. These govern the line widths for the relevant elements, and behave the same way as the regular <code>lwd</code> parameter. The only thing to note is that the default value for <code>medlwd</code> value is three times the value of the others.</li>
<li><em>Line colour:</em> <code>boxcol, medcol, whiskcol, staplecol, outcol</code>. These govern the colour of the lines used to draw the relevant elements. Specify a colour in the same way that you usually do.</li>
<li><em>Fill colour:</em> <code>boxfill</code>. What colour should we use to fill the box?</li>
<li><em>Point character:</em> <code>medpch, outpch</code>. These behave like the regular <code>pch</code> parameter used to select the plot character. Note that you can set <code>outpch = NA</code> to stop R from plotting the outliers at all, and you can also set <code>medpch = NA</code> to stop it from drawing a character for the median (this is the default!)</li>
<li><em>Point expansion:</em> <code>medcex, outcex</code>. Size parameters for the points used to plot medians and outliers. These are only meaningful if the corresponding points are actually plotted. So for the default boxplot, which includes outlier points but uses a line rather than a point to draw the median, only the <code>outcex</code> parameter is meaningful.</li>
<li><em>Background colours:</em> <code>medbg, outbg</code>. Again, the background colours are only meaningful if the points are actually plotted.</li>
</ul>
<p>Taken as a group, these parameters allow you almost complete freedom to select the graphical style for your boxplot that you feel is most appropriate to the data set you’re trying to describe. That said, when you’re first starting out there’s no shame in using the default settings! But if you want to master the art of designing beautiful figures, it helps to try playing around with these parameters to see what works and what doesn’t. Finally, I should mention a few other arguments that you might want to make use of:</p>
<ul>
<li><code>horizontal</code>. Set this to <code>TRUE</code> to display the plot horizontally rather than vertically.</li>
<li><code>varwidth</code>. Set this to <code>TRUE</code> to get R to scale the width of each box so that the areas are proportional to the number of observations that contribute to the boxplot. This is only useful if you’re drawing multiple boxplots at once (see Section @ref(multipleboxplots).</li>
<li><code>show.names</code>. Set this to <code>TRUE</code> to get R to attach labels to the boxplots.</li>
<li><code>notch</code>. If you set <code>notch = TRUE</code>, R will draw little notches in the sides of each box. If the notches of two boxplots don’t overlap, then there is a “statistically significant” difference between the corresponding medians. If you haven’t read Chapter @ref(hypothesistesting), ignore this argument – we haven’t discussed statistical significance, so this doesn’t mean much to you. I’m mentioning it only because you might want to come back to the topic later on. (see also the <code>notch.frac</code> option when you type <code>?bxp</code>).</li>
</ul>
</section>
<section id="boxplotoutliers" class="level3">
<h3 class="anchored" data-anchor-id="boxplotoutliers">Using box plots to detect outliers</h3>
<p>Because the boxplot automatically (unless you change the <code>range</code> argument) separates out those observations that lie within a certain range, people often use them as an informal method for detecting <strong><em>outliers</em></strong>: observations that are “suspiciously” distant from the rest of the data. Here’s an example. Suppose that I’d drawn the boxplot for the AFL margins data, and it came up looking like Figure @ref(fig:boxplotoutlier).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/boxplotoutlier-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A boxplot showing one very suspicious outlier! I’ve drawn this plot in a similar, minimalist style to the one in Figure @ref(fig:boxplot2b), but I’ve used the <code>horizontal</code> argument to draw it sideways in order to save space.</figcaption>
</figure>
</div>
</div>
</div>
<p>It’s pretty clear that something funny is going on with one of the observations. Apparently, there was one game in which the margin was over 300 points! That doesn’t sound right to me. Now that I’ve become suspicious, it’s time to look a bit more closely at the data. One function that can be handy for this is the <code>which()</code> function; it takes as input a vector of logicals, and outputs the indices of the <code>TRUE</code> cases. This is particularly useful in the current context because it lets me do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>suspicious.cases <span class="ot">&lt;-</span> afl.margins <span class="sc">&gt;</span> <span class="dv">300</span></span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="fu">which</span>( suspicious.cases )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 137</code></pre>
</div>
</div>
<p>although in real life I probably wouldn’t bother creating the <code>suspicious.cases</code> variable: I’d just cut out the middle man and use a command like <code>which( afl.margins &gt; 300 )</code>. In any case, what this has done is shown me that the outlier corresponds to game 137. Then, I find the recorded margin for that game:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>afl.margins[<span class="dv">137</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 333</code></pre>
</div>
</div>
<p>Hm. That definitely doesn’t sound right. So then I go back to the original data source (the internet!) and I discover that the actual margin of that game was 33 points. Now it’s pretty clear what happened. Someone must have typed in the wrong number. Easily fixed, just by typing <code>afl.margins[137] &lt;- 33</code>. While this might seem like a silly example, I should stress that this kind of thing actually happens a lot. Real world data sets are often riddled with stupid errors, especially when someone had to type something into a computer at some point. In fact, there’s actually a name for this phase of data analysis, since in practice it can waste a huge chunk of our time: <strong><em>data cleaning</em></strong>. It involves searching for typos, missing data and all sorts of other obnoxious errors in raw data files.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>What about the real data? Does the value of 116 constitute a funny observation not? Possibly. As it turns out the game in question was Fremantle v Hawthorn, and was played in round 21 (the second last home and away round of the season). Fremantle had already qualified for the final series and for them the outcome of the game was irrelevant; and the team decided to rest several of their star players. As a consequence, Fremantle went into the game severely underpowered. In contrast, Hawthorn had started the season very poorly but had ended on a massive winning streak, and for them a win could secure a place in the finals. With the game played on Hawthorn’s home turf<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> and with so many unusual factors at play, it is perhaps no surprise that Hawthorn annihilated Fremantle by 116 points. Two weeks later, however, the two teams met again in an elimination final on Fremantle’s home ground, and Fremantle won comfortably by 30 points.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>So, should we exclude the game from subsequent analyses? If this were a psychology experiment rather than an AFL season, I’d be quite tempted to exclude it because there’s pretty strong evidence that Fremantle weren’t really trying very hard: and to the extent that my research question is based on an assumption that participants are genuinely trying to do the task. On the other hand, in a lot of studies we’re actually interested in seeing the full range of possible behaviour, and that includes situations where people decide not to try very hard: so excluding that observation would be a bad idea. In the context of the AFL data, a similar distinction applies. If I’d been trying to make tips about who would perform well in the finals, I would have (and in fact did) disregard the Round 21 massacre, because it’s way too misleading. On the other hand, if my interest is solely in the home and away season itself, I think it would be a shame to throw away information pertaining to one of the most distinctive (if boring) games of the year. In other words, the decision about whether to include outliers or exclude them depends heavily on <em>why</em> you think the data look they way they do, and what you want to use the data <em>for</em>. Statistical tools can provide an automatic method for suggesting candidates for deletion, but you really need to exercise good judgment here. As I’ve said before, R is a mindless automaton. It doesn’t watch the footy, so it lacks the broader context to make an informed decision. You are <em>not</em> a mindless automaton, so you should exercise judgment: if the outlier looks legitimate to you, then keep it. In any case, I’ll return to the topic again in Section @ref(regressiondiagnostics), so let’s return to our discussion of how to draw boxplots.</p>
</section>
<section id="multipleboxplots" class="level3">
<h3 class="anchored" data-anchor-id="multipleboxplots">Drawing multiple boxplots</h3>
<p>One last thing. What if you want to draw multiple boxplots at once? Suppose, for instance, I wanted separate boxplots showing the AFL margins not just for 2010, but for every year between 1987 and 2010. To do that, the first thing we’ll have to do is find the data. These are stored in the <code>aflsmall2.Rdata</code> file. So let’s load it and take a quick peek at what’s inside:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">load</span>( <span class="st">""</span>materials<span class="sc">/</span>data<span class="sc">/</span>aflsmall2.Rdata<span class="st">""</span> )</span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="fu">who</span>( <span class="cn">TRUE</span> )</span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="co">#   -- Name --   -- Class --   -- Size --</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="co">#   afl2         data.frame    4296 x 2  </span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="co">#    $margin     numeric       4296      </span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="co">#    $year       numeric       4296     </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that <code>afl2</code> data frame is pretty big. It contains 4296 games, which is far more than I want to see printed out on my computer screen. To that end, R provides you with a few useful functions to print out only a few of the row in the data frame. The first of these is <code>head()</code> which prints out the first 6 rows, of the data frame, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">head</span>( afl2 )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  margin year
1     33 1987
2     59 1987
3     45 1987
4     91 1987
5     39 1987
6      1 1987</code></pre>
</div>
</div>
<p>You can also use the <code>tail()</code> function to print out the last 6 rows. The <code>car</code> package also provides a handy little function called <code>some()</code> which prints out a random subset of the rows.</p>
<p>In any case, the important thing is that we have the <code>afl2</code> data frame which contains the variables that we’re interested in. What we want to do is have R draw boxplots for the <code>margin</code> variable, plotted separately for each separate <code>year</code>. The way to do this using the <code>boxplot()</code> function is to input a <code>formula</code> rather than a variable as the input. In this case, the formula we want is <code>margin ~ year</code>. So our boxplot command now looks like this. The result is shown in Figure @ref(fig:multipleboxplots).<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">boxplot</span>( <span class="at">formula =</span> margin <span class="sc">~</span> year,</span>
<span id="cb29-2"><a href="#cb29-2"></a>         <span class="at">data =</span> afl2</span>
<span id="cb29-3"><a href="#cb29-3"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/multipleboxplots-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Boxplots showing the AFL winning margins for the 24 years from 1987 to 2010 inclusive. This is the default plot created by R, with no annotations added and no changes to the visual design. It’s pretty readable, though at a minimum you’d want to include some basic annotations labelling the axes. Compare and contrast with Figure @ref(fig:multipleboxplots2)</figcaption>
</figure>
</div>
</div>
</div>
<p>Even this, the default version of the plot, gives a sense of why it’s sometimes useful to choose boxplots instead of histograms. Even before taking the time to turn this basic output into something more readable, it’s possible to get a good sense of what the data look like from year to year without getting overwhelmed with too much detail. Now imagine what would have happened if I’d tried to cram 24 histograms into this space: no chance at all that the reader is going to learn anything useful.</p>
<p>That being said, the default boxplot leaves a great deal to be desired in terms of visual clarity. The outliers are too visually prominent, the dotted lines look messy, and the interesting content (i.e., the behaviour of the median and the interquartile range across years) gets a little obscured. Fortunately, this is easy to fix, since we’ve already covered a lot of tools you can use to customise your output. After playing around with several different versions of the plot, the one I settled on is shown in Figure @ref(fig:multipleboxplots2). The command I used to produce it is long, but not complicated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">boxplot</span>( <span class="at">formula =</span>  margin <span class="sc">~</span> year,   <span class="co"># the formula</span></span>
<span id="cb30-2"><a href="#cb30-2"></a>           <span class="at">data =</span> afl2,                <span class="co"># the data set</span></span>
<span id="cb30-3"><a href="#cb30-3"></a>           <span class="at">xlab =</span> <span class="st">"AFL season"</span>,        <span class="co"># x axis label</span></span>
<span id="cb30-4"><a href="#cb30-4"></a>           <span class="at">ylab =</span> <span class="st">"Winning Margin"</span>,    <span class="co"># y axis label</span></span>
<span id="cb30-5"><a href="#cb30-5"></a>           <span class="at">frame.plot =</span> <span class="cn">FALSE</span>,         <span class="co"># don't draw a frame</span></span>
<span id="cb30-6"><a href="#cb30-6"></a>           <span class="at">staplewex =</span> <span class="dv">0</span>,              <span class="co"># don't draw staples</span></span>
<span id="cb30-7"><a href="#cb30-7"></a>           <span class="at">staplecol =</span> <span class="st">"white"</span>,        <span class="co"># (fixes a tiny display issue)</span></span>
<span id="cb30-8"><a href="#cb30-8"></a>           <span class="at">boxwex =</span> .<span class="dv">75</span>,               <span class="co"># narrow the boxes slightly</span></span>
<span id="cb30-9"><a href="#cb30-9"></a>           <span class="at">boxfill =</span> <span class="st">"grey80"</span>,         <span class="co"># lightly shade the boxes</span></span>
<span id="cb30-10"><a href="#cb30-10"></a>           <span class="at">whisklty =</span> <span class="dv">1</span>,               <span class="co"># solid line for whiskers </span></span>
<span id="cb30-11"><a href="#cb30-11"></a>           <span class="at">whiskcol =</span> <span class="st">"grey70"</span>,        <span class="co"># dim the whiskers</span></span>
<span id="cb30-12"><a href="#cb30-12"></a>           <span class="at">boxcol =</span> <span class="st">"grey70"</span>,          <span class="co"># dim the box borders</span></span>
<span id="cb30-13"><a href="#cb30-13"></a>           <span class="at">outcol =</span> <span class="st">"grey70"</span>,          <span class="co"># dim the outliers</span></span>
<span id="cb30-14"><a href="#cb30-14"></a>           <span class="at">outpch =</span> <span class="dv">20</span>,                <span class="co"># outliers as solid dots</span></span>
<span id="cb30-15"><a href="#cb30-15"></a>           <span class="at">outcex =</span> .<span class="dv">5</span>,                <span class="co"># shrink the outliers</span></span>
<span id="cb30-16"><a href="#cb30-16"></a>           <span class="at">medlty =</span> <span class="st">"blank"</span>,           <span class="co"># no line for the medians</span></span>
<span id="cb30-17"><a href="#cb30-17"></a>           <span class="at">medpch =</span> <span class="dv">20</span>,                <span class="co"># instead, draw solid dots</span></span>
<span id="cb30-18"><a href="#cb30-18"></a>           <span class="at">medlwd =</span> <span class="fl">1.5</span>                <span class="co"># make them larger</span></span>
<span id="cb30-19"><a href="#cb30-19"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/multipleboxplots2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A cleaned up version of Figure @ref(fig:multipleboxplots). Notice that I’ve used a very minimalist design for the boxplots, so as to focus the eye on the medians. I’ve also converted the medians to solid dots, to convey a sense that year to year variation in the median should be thought of as a single coherent plot (similar to what we did when plotting the <code>Fibonacci</code> variable earlier). The size of outliers has been shrunk, because they aren’t actually very interesting. In contrast, I’ve added a fill colour to the boxes, to make it easier to look at the trend in the interquartile range across years.</figcaption>
</figure>
</div>
</div>
</div>
<p>Of course, given that the command is that long, you might have guessed that I didn’t spend ages typing all that rubbish in over and over again. Instead, I wrote a script, which I kept tweaking until it produced the figure that I wanted. We’ll talk about scripts later in Section @ref(scripts), but given the length of the command I thought I’d remind you that there’s an easier way of trying out different commands than typing them all in over and over.</p>
</section>
</section>
<section id="scatterplots" class="level2">
<h2 class="anchored" data-anchor-id="scatterplots">Scatterplots</h2>
<p><strong><em>Scatterplots</em></strong> are a simple but effective tool for visualising data. We’ve already seen scatterplots in this chapter, when using the <code>plot()</code> function to draw the <code>Fibonacci</code> variable as a collection of dots (Section @ref(introplotting). However, for the purposes of this section I have a slightly different notion in mind. Instead of just plotting one variable, what I want to do with my scatterplot is display the relationship between <em>two</em> variables, like we saw with the figures in the section on correlation (Section @ref(correl). It’s this latter application that we usually have in mind when we use the term “scatterplot”. In this kind of plot, each observation corresponds to one dot: the horizontal location of the dot plots the value of the observation on one variable, and the vertical location displays its value on the other variable. In many situations you don’t really have a clear opinions about what the <em>causal</em> relationship is (e.g., does A cause B, or does B cause A, or does some other variable C control both A and B). If that’s the case, it doesn’t really matter which variable you plot on the x-axis and which one you plot on the y-axis. However, in many situations you do have a pretty strong idea which variable you think is most likely to be causal, or at least you have some suspicions in that direction. If so, then it’s conventional to plot the cause variable on the x-axis, and the effect variable on the y-axis. With that in mind, let’s look at how to draw scatterplots in R, using the same <code>parenthood</code> data set (i.e.&nbsp;<code>parenthood.Rdata</code>) that I used when introducing the idea of correlations.</p>
<p>Suppose my goal is to draw a scatterplot displaying the relationship between the amount of sleep that I get (<code>dan.sleep</code>) and how grumpy I am the next day (<code>dan.grump</code>). As you might expect given our earlier use of <code>plot()</code> to display the <code>Fibonacci</code> data, the function that we use is the <code>plot()</code> function, but because it’s a generic function all the hard work is still being done by the <code>plot.default()</code> function. In any case, there are two different ways in which we can get the plot that we’re after. The first way is to specify the name of the variable to be plotted on the <code>x</code> axis and the variable to be plotted on the <code>y</code> axis. When we do it this way, the command looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">plot</span>( <span class="at">x =</span> parenthood<span class="sc">$</span>dan.sleep,   <span class="co"># data on the x-axis</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>      <span class="at">y =</span> parenthood<span class="sc">$</span>dan.grump    <span class="co"># data on the y-axis</span></span>
<span id="cb31-3"><a href="#cb31-3"></a> )  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/scattera-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>the default scatterplot that R produces</figcaption>
</figure>
</div>
</div>
</div>
<p>The second way do to it is to use a “formula and data frame” format, but I’m going to avoid using it.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> For now, let’s just stick with the <code>x</code> and <code>y</code> version. If we do this, the result is the very basic scatterplot shown in Figure @ref(fig:scattera). This serves fairly well, but there’s a few customisations that we probably want to make in order to have this work properly. As usual, we want to add some labels, but there’s a few other things we might want to do as well. Firstly, it’s sometimes useful to rescale the plots. In Figure @ref(fig:scattera) R has selected the scales so that the data fall neatly in the middle. But, in this case, we happen to know that the grumpiness measure falls on a scale from 0 to 100, and the hours slept falls on a natural scale between 0 hours and about 12 or so hours (the longest I can sleep in real life). So the command I might use to draw this is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">plot</span>( <span class="at">x =</span> parenthood<span class="sc">$</span>dan.sleep,          <span class="co"># data on the x-axis</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>       <span class="at">y =</span> parenthood<span class="sc">$</span>dan.grump,         <span class="co"># data on the y-axis</span></span>
<span id="cb32-3"><a href="#cb32-3"></a>       <span class="at">xlab =</span> <span class="st">"My sleep (hours)"</span>,        <span class="co"># x-axis label</span></span>
<span id="cb32-4"><a href="#cb32-4"></a>       <span class="at">ylab =</span> <span class="st">"My grumpiness (0-100)"</span>,   <span class="co"># y-axis label</span></span>
<span id="cb32-5"><a href="#cb32-5"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">12</span>),                   <span class="co"># scale the x-axis</span></span>
<span id="cb32-6"><a href="#cb32-6"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),                  <span class="co"># scale the y-axis</span></span>
<span id="cb32-7"><a href="#cb32-7"></a>       <span class="at">pch =</span> <span class="dv">20</span>,                         <span class="co"># change the plot type</span></span>
<span id="cb32-8"><a href="#cb32-8"></a>       <span class="at">col =</span> <span class="st">"gray50"</span>,                   <span class="co"># dim the dots slightly</span></span>
<span id="cb32-9"><a href="#cb32-9"></a>       <span class="at">frame.plot =</span> <span class="cn">FALSE</span>                <span class="co"># don't draw a box</span></span>
<span id="cb32-10"><a href="#cb32-10"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This command produces the scatterplot in Figure @ref(fig:scatterb), or at least very nearly. What it doesn’t do is draw the line through the middle of the points. Sometimes it can be very useful to do this, and I can do so using <code>lines()</code>, which is a low level plotting function. Better yet, the arguments that I need to specify are pretty much the exact same ones that I use when calling the <code>plot()</code> function. That is, suppose that I want to draw a line that goes from the point (4,93) to the point (9.5,37). Then the <code>x</code> locations can be specified by the vector <code>c(4,9.5)</code> and the <code>y</code> locations correspond to the vector <code>c(93,37)</code>. In other words, I use this command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">plot</span>( <span class="at">x =</span> parenthood<span class="sc">$</span>dan.sleep,          <span class="co"># data on the x-axis</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>       <span class="at">y =</span> parenthood<span class="sc">$</span>dan.grump,         <span class="co"># data on the y-axis</span></span>
<span id="cb33-3"><a href="#cb33-3"></a>       <span class="at">xlab =</span> <span class="st">"My sleep (hours)"</span>,        <span class="co"># x-axis label</span></span>
<span id="cb33-4"><a href="#cb33-4"></a>       <span class="at">ylab =</span> <span class="st">"My grumpiness (0-100)"</span>,   <span class="co"># y-axis label</span></span>
<span id="cb33-5"><a href="#cb33-5"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">12</span>),                   <span class="co"># scale the x-axis</span></span>
<span id="cb33-6"><a href="#cb33-6"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),                  <span class="co"># scale the y-axis</span></span>
<span id="cb33-7"><a href="#cb33-7"></a>       <span class="at">pch =</span> <span class="dv">20</span>,                         <span class="co"># change the plot type</span></span>
<span id="cb33-8"><a href="#cb33-8"></a>       <span class="at">col =</span> <span class="st">"gray50"</span>,                   <span class="co"># dim the dots slightly</span></span>
<span id="cb33-9"><a href="#cb33-9"></a>       <span class="at">frame.plot =</span> <span class="cn">FALSE</span>                <span class="co"># don't draw a box</span></span>
<span id="cb33-10"><a href="#cb33-10"></a>)</span>
<span id="cb33-11"><a href="#cb33-11"></a> <span class="fu">lines</span>( <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="fl">9.5</span>),   <span class="co"># the horizontal locations</span></span>
<span id="cb33-12"><a href="#cb33-12"></a>        <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">93</span>,<span class="dv">37</span>),   <span class="co"># the vertical locations</span></span>
<span id="cb33-13"><a href="#cb33-13"></a>        <span class="at">lwd =</span> <span class="dv">2</span>         <span class="co"># line width</span></span>
<span id="cb33-14"><a href="#cb33-14"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/scatterb-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A scatterplot with scatter plot specific customisations</figcaption>
</figure>
</div>
</div>
</div>
<p>And when I do so, R plots the line over the top of the plot that I drew using the previous command. In most realistic data analysis situations you absolutely don’t want to just guess where the line through the points goes, since there’s about a billion different ways in which you can get R to do a better job. However, it does at least illustrate the basic idea.</p>
<p>One possibility, if you do want to get R to draw nice clean lines through the data for you, is to use the <code>scatterplot()</code> function in the <code>car</code> package. Before we can use <code>scatterplot()</code> we need to load the package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">library</span>( car )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
</div>
<p>Having done so, we can now use the function. The command we need is this one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">scatterplot</span>( dan.grump <span class="sc">~</span> dan.sleep,</span>
<span id="cb36-2"><a href="#cb36-2"></a>              <span class="at">data =</span> parenthood, </span>
<span id="cb36-3"><a href="#cb36-3"></a>              <span class="at">smooth =</span> <span class="cn">FALSE</span></span>
<span id="cb36-4"><a href="#cb36-4"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/fancyscatter-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A fancy scatterplot drawn using the <code>scatterplot()</code> function in the <code>car</code> package.</figcaption>
</figure>
</div>
</div>
</div>
<p>The first two arguments should be familiar: the first input is a formula <code>dan.grump ~ dan.sleep</code> telling R what variables to plot,<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> and the second specifies a <code>data</code> frame. The third argument <code>smooth</code> I’ve set to <code>FALSE</code> to stop the <code>scatterplot()</code> function from drawing a fancy “smoothed” trendline (since it’s a bit confusing to beginners). The scatterplot itself is shown in Figure @ref(fig:fancyscatter). As you can see, it’s not only drawn the scatterplot, but its also drawn boxplots for each of the two variables, as well as a simple line of best fit showing the relationship between the two variables.</p>
<section id="more-elaborate-options" class="level3">
<h3 class="anchored" data-anchor-id="more-elaborate-options">More elaborate options</h3>
<p>Often you find yourself wanting to look at the relationships between several variables at once. One useful tool for doing so is to produce a <strong><em>scatterplot matrix</em></strong>, analogous to the correlation matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">cor</span>( <span class="at">x =</span> parenthood ) <span class="co"># calculate correlation matrix</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             dan.sleep  baby.sleep   dan.grump         day
dan.sleep   1.00000000  0.62794934 -0.90338404 -0.09840768
baby.sleep  0.62794934  1.00000000 -0.56596373 -0.01043394
dan.grump  -0.90338404 -0.56596373  1.00000000  0.07647926
day        -0.09840768 -0.01043394  0.07647926  1.00000000</code></pre>
</div>
</div>
<p>We can get a the corresponding scatterplot matrix by using the <code>pairs()</code> function:<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">pairs</span>( <span class="at">x =</span> parenthood ) <span class="co"># draw corresponding scatterplot matrix  </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/pairs-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>A scatterplot matrix from the `pairs() function</figcaption>
</figure>
</div>
</div>
</div>
<p>The output of the <code>pairs()</code> command is shown in Figure @ref(fig:pairs). An alternative way of calling the <code>pairs()</code> function, which can be useful in some situations, is to specify the variables to include using a one-sided formula. For instance, this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">pairs</span>( <span class="at">formula =</span> <span class="sc">~</span> dan.sleep <span class="sc">+</span> baby.sleep <span class="sc">+</span> dan.grump,</span>
<span id="cb40-2"><a href="#cb40-2"></a>        <span class="at">data =</span> parenthood</span>
<span id="cb40-3"><a href="#cb40-3"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>would produce a <span class="math inline">\(3 \times 3\)</span> scatterplot matrix that only compare <code>dan.sleep</code>, <code>dan.grump</code> and <code>baby.sleep</code>. Obviously, the first version is much easier, but there are cases where you really only want to look at a few of the variables, so it’s nice to use the formula interface.</p>
</section>
</section>
<section id="bargraph" class="level2">
<h2 class="anchored" data-anchor-id="bargraph">Bar graphs</h2>
<p>Another form of graph that you often want to plot is the <strong><em>bar graph</em></strong>. The main function that you can use in R to draw them is the <code>barplot()</code> function.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> And to illustrate the use of the function, I’ll use the <code>finalists</code> variable that I introduced in Section @ref(mode). What I want to do is draw a bar graph that displays the number of finals that each team has played in over the time spanned by the <code>afl</code> data set. So, let’s start by creating a vector that contains this information. I’ll use the <code>tabulate()</code> function to do this (which will be discussed properly in Section @ref(freqtables), since it creates a simple numeric vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">tabulate</span>( afl.finalists )</span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">print</span>( freq )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 26 25 26 28 32  0  6 39 27 28 28 17  6 24 26 38 24</code></pre>
</div>
</div>
<p>This isn’t exactly the prettiest of frequency tables, of course. I’m only doing it this way so that you can see the <code>barplot()</code> function in it’s “purest” form: when the input is just an ordinary numeric vector. That being said, I’m obviously going to need the team names to create some labels, so let’s create a variable with those. I’ll do this using the <code>levels()</code> function, which outputs the names of all the levels of a factor (see Section @ref(factors):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>teams <span class="ot">&lt;-</span> <span class="fu">levels</span>( afl.finalists )</span>
<span id="cb43-2"><a href="#cb43-2"></a><span class="fu">print</span>( teams )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Adelaide"         "Brisbane"         "Carlton"          "Collingwood"     
 [5] "Essendon"         "Fitzroy"          "Fremantle"        "Geelong"         
 [9] "Hawthorn"         "Melbourne"        "North Melbourne"  "Port Adelaide"   
[13] "Richmond"         "St Kilda"         "Sydney"           "West Coast"      
[17] "Western Bulldogs"</code></pre>
</div>
</div>
<p>Okay, so now that we have the information we need, let’s draw our bar graph. The main argument that you need to specify for a bar graph is the <code>height</code> of the bars, which in our case correspond to the values stored in the <code>freq</code> variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">barplot</span>( <span class="at">height =</span> freq )  <span class="co"># specifying the argument name</span></span>
<span id="cb45-2"><a href="#cb45-2"></a><span class="fu">barplot</span>( freq )           <span class="co"># the lazier version</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Either of these two commands will produce the simple bar graph shown in Figure @ref(fig:bar1a).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/bar1a-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>the simplest version of a bargraph, containing the data but no labels</figcaption>
</figure>
</div>
</div>
</div>
<p>As you can see, R has drawn a pretty minimal plot. It doesn’t have any labels, obviously, because we didn’t actually tell the <code>barplot()</code> function what the labels are! To do this, we need to specify the <code>names.arg</code> argument. The <code>names.arg</code> argument needs to be a vector of character strings containing the text that needs to be used as the label for each of the items. In this case, the <code>teams</code> vector is exactly what we need, so the command we’re looking for is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>    <span class="fu">barplot</span>( <span class="at">height =</span> freq, <span class="at">names.arg =</span> teams ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/bar1b-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>we’ve added the labels, but because the text runs horizontally R only includes a few of them</figcaption>
</figure>
</div>
</div>
</div>
<p>This is an improvement, but not much of an improvement. R has only included a few of the labels, because it can’t fit them in the plot. This is the same behaviour we saw earlier with the multiple-boxplot graph in Figure @ref(fig:multipleboxplots). However, in Figure @ref(fig:multipleboxplots) it wasn’t an issue: it’s pretty obvious from inspection that the two unlabelled plots in between 1987 and 1990 must correspond to the data from 1988 and 1989. However, the fact that <code>barplot()</code> has omitted the names of every team in between Adelaide and Fitzroy is a lot more problematic.</p>
<p>The simplest way to fix this is to rotate the labels, so that the text runs vertically not horizontally. To do this, we need to alter set the <code>las</code> parameter, which I discussed briefly in Section @ref(introplotting). What I’ll do is tell R to rotate the text so that it’s always perpendicular to the axes (i.e., I’ll set <code>las = 2</code>). When I do that, as per the following command…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>    <span class="fu">barplot</span>(<span class="at">height =</span> freq,  <span class="co"># the frequencies</span></span>
<span id="cb47-2"><a href="#cb47-2"></a>            <span class="at">names.arg =</span> teams,  <span class="co"># the label</span></span>
<span id="cb47-3"><a href="#cb47-3"></a>            <span class="at">las =</span> <span class="dv">2</span>)            <span class="co"># rotate the labels</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals_files/figure-html/bar1c-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>we’ve rotated the labels, but now the text is too long to fit</figcaption>
</figure>
</div>
</div>
</div>
<p>… the result is the bar graph shown in Figure @ref(fig:bar1c). We’ve fixed the problem, but we’ve created a new one: the axis labels don’t quite fit anymore. To fix this, we have to be a bit cleverer again. A simple fix would be to use shorter names rather than the full name of all teams, and in many situations that’s probably the right thing to do. However, at other times you really do need to create a bit more space to add your labels, so I’ll show you how to do that.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Perhaps I’m a simple minded person, but I love pictures. Every time I write a new scientific paper, one of the first things I do is sit down and think about what the pictures will be. In my head, an article is really just a sequence of pictures, linked together by a story. All the rest of it is just window dressing. What I’m really trying to say here is that the human visual system is a very powerful data analysis tool. Give it the right kind of information and it will supply a human reader with a massive amount of knowledge very quickly. Not for nothing do we have the saying “a picture is worth a thousand words”. With that in mind, I think that this is one of the most important chapters in the book. The topics covered were:</p>
<ul>
<li><em>Basic overview to R graphics</em>. In Section @ref(rgraphics) we talked about how graphics in R are organised, and then moved on to the basics of how they’re drawn in Section @ref(introplotting).</li>
<li><em>Common plots</em>. Much of the chapter was focused on standard graphs that statisticians like to produce: histograms (Section @ref(hist)), stem and leaf plots (Section @ref(stem)), boxplots (Section @ref(boxplots)), scatterplots (Section @ref(scatterplots)) and bar graphs (Section @ref(bargraph)).</li>
<li><em>Saving image files</em>. The last part of the chapter talked about how to export your pictures (Section @ref(saveimage))</li>
</ul>
<p>One final thing to point out. At the start of the chapter I mentioned that R has several completely distinct systems for drawing figures. In this chapter I’ve focused on the <em>traditional</em> graphics system. It’s the easiest one to get started with: you can draw a histogram with a command as simple as <code>hist(x)</code>. However, it’s not the most powerful tool for the job, and after a while most R users start looking to shift to fancier systems. One of the most popular graphics systems is provided by the <code>ggplot2</code> package (see ), which is loosely based on “The grammar of graphics” <span class="citation" data-cites="Wilkinson2006">[@Wilkinson2006]</span>. It’s not for novices: you need to have a pretty good grasp of R before you can start using it, and even then it takes a while to really get the hang of it. But when you’re finally at that stage, it’s worth taking the time to teach yourself, because it’s a much cleaner system.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The origin of this quote is Tufte’s lovely book <em>The Visual Display of Quantitative Information</em>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The low-level function that does this is called <code>title()</code> in case you ever need to know, and you can type <code>?title</code> to find out a bit more detail about what these arguments do.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>On the off chance that this isn’t enough freedom for you, you can select a colour directly as a “red, green, blue” specification using the <code>rgb()</code> function, or as a “hue, saturation, value” specification using the <code>hsv()</code> function.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Also, there’s a low level function called <code>axis()</code> that allows a lot more control over the appearance of the axes.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>R being what it is, it’s no great surprise that there’s also a <code>fivenum()</code> function that does much the same thing.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>I realise there’s a kind of logic to the way R names are constructed, but they still sound dumb. When I typed this sentence, all I could think was that it sounded like the name of a kids movie if it had been written by Lewis Carroll: “The frabjous gambolles of Staplewex and Whisklty” or something along those lines.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Sometimes it’s convenient to have the boxplot automatically label the outliers for you. The original <code>boxplot()</code> function doesn’t allow you to do this; however, the <code>Boxplot()</code> function in the <code>car</code> package does. The design of the <code>Boxplot()</code> function is very similar to <code>boxplot()</code>. It just adds a few new arguments that allow you to tweak the labelling scheme. I’ll leave it to the reader to check this out.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Sort of. The game was played in Launceston, which is a de facto home away from home for Hawthorn.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Contrast this situation with the next largest winning margin in the data set, which was Geelong’s 108 point demolition of Richmond in round 6 at their home ground, Kardinia Park. Geelong have been one of the most dominant teams over the last several years, a period during which they strung together an incredible 29-game winning streak at Kardinia Park. Richmond have been useless for several years. This is in no meaningful sense an outlier. Geelong have been winning by these margins (and Richmond losing by them) for quite some time. Frankly I’m surprised that the result wasn’t more lopsided: as happened to Melbourne in 2011 when Geelong won by a modest 186 points.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Actually, there’s other ways to do this. If the input argument <code>x</code> is a list object (see Section @ref(lists), the <code>boxplot()</code> function will draw a separate boxplot for each variable in that list. Relatedly, since the <code>plot()</code> function – which we’ll discuss shortly – is a generic (see Section @ref(generics), you might not be surprised to learn that one of its special cases is a boxplot: specifically, if you use <code>plot()</code> where the first argument <code>x</code> is a factor and the second argument <code>y</code> is numeric, then the result will be a boxplot, showing the values in <code>y</code>, with a separate boxplot for each level. For instance, something like <code>plot(x = afl2\$year, y = afl2\$margin)</code> would work. <a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The reason is that there’s an annoying design flaw in the way the <code>plot()</code> function handles this situation. The problem is that the <code>plot.formula()</code> function uses different names to for the arguments than the <code>plot()</code> function expects. As a consequence, you can’t specify the formula argument by name. If you just specify a formula as the first argument without using the name it works fine, because the <code>plot()</code> function thinks the formula corresponds to the <code>x</code> argument, and the <code>plot.formula()</code> function thinks it corresponds to the <code>formula</code> argument; and surprisingly, everything works nicely. But the moment that you, the user, tries to be unambiguous about the name, one of those two functions is going to cry.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>You might be wondering why I haven’t specified the argument name for the formula. The reason is that there’s a bug in how the <code>scatterplot()</code> function is written: under the hood there’s one function that expects the argument to be named <code>x</code> and another one that expects it to be called <code>formula</code>. I don’t know why the function was written this way, but it’s not an isolated problem: this particular kind of bug repeats itself in a couple of other functions (you’ll see it again in Chapter @ref(ttest). The solution in such cases is to omit the argument name: that way, one function “thinks” that you’ve specified <code>x</code> and the other one “thinks” you’ve specified <code>formula</code> and everything works the way it’s supposed to. It’s not a great state of affairs, I’ll admit, but it sort of works.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Yet again, we could have produced this output using the <code>plot()</code> function: when the <code>x</code> argument is a data frame containing numeric variables only, then the output is a scatterplot matrix. So, once again, what I could have done is just type <code>plot( parenthood )</code>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Once again, it’s worth noting the link to the generic <code>plot()</code> function. If the <code>x</code> argument to <code>plot()</code> is a factor (and no <code>y</code> argument is given), the result is a bar graph. So you could use <code>plot( afl.finalists )</code> and get the same output as <code>barplot( afl.finalists )</code>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2024, Gordon Wright</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>